### ISSUE TITLE
Custom redirects

### ISSUE THREAD

**Issue by ghost** [mataroablog/mataroa#11]
Hi! I really like the project and am considering moving my blog to it. The thing that's stopping me is that you cannot add custom redirects. One example: My current blog uses `example.com/post/slug-name`. If I moved to Mataroa (which uses `example.com/blog/slug-name`), many incoming links would be broken.

I know Mataroa is meant to be as simple as possible, but this could be an issue for many users migrating.

**Comment by sirodoht** [comment]
Hi @ruhrscholz. Good point. I have just deployed a feature to redirect all `/post/slug-name/` to `/blog/slug-name/`. I'd rather not add a fully featured redirect functionality (although I might consider it in the future) but I think it's ok enough to redirect this kind of paths, since `post` is common for blogs as well.

Hopefully this solves your problem?

**Comment by ghost** [comment]
Thanks! This should resolve issues when moving from a default Hugo (and I believe Jekyll, and some other SSGs) setup.
